# Generated by Django 2.1.7 on 2019-03-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('family_relation', models.CharField(max_length=10)),
                ('family_relation_name', models.CharField(max_length=10)),
                ('family_contact_number', models.CharField(max_length=20)),
                ('donation_status', models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=20)),
                ('upload_medical_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('donated_before', models.BooleanField()),
                ('family_consent', models.BooleanField()),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='donation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.DonationRequests'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
