# Generated by Django 2.1.7 on 2019-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Appointments',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='DonationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('family_relation', models.CharField(max_length=10)),
                ('family_relation_name', models.CharField(max_length=10)),
                ('family_contact_number', models.CharField(max_length=20)),
                ('donation_status', models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=20)),
                ('upload_medical_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('donated_before', models.BooleanField()),
                ('family_consent', models.BooleanField()),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation Requests',
                'verbose_name_plural': 'Donation Requests',
            },
        ),
    ]
