# Generated by Django 2.1.7 on 2019-03-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequests',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='donation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.DonationRequests'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
