# Generated by Django 2.1.7 on 2019-03-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Not Booked', max_length=20),
            preserve_default=False,
        ),
    ]
