# Generated by Django 2.1.7 on 2019-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_auto_20190316_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name': 'Appointments', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='donationrequests',
            options={'verbose_name': 'Donation Requests', 'verbose_name_plural': 'Donation Requests'},
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Not Booked', max_length=20),
            preserve_default=False,
        ),
    ]
