# Generated by Django 2.1.7 on 2019-03-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.IntegerField()),
                ('donor', models.CharField(max_length=100)),
                ('organ', models.CharField(max_length=75)),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
    ]
